apiVersion: fs.functionstream.github.io/v1alpha1
kind: Function
metadata:
  name: current-time-function
spec:
  displayName: Get Current Time Function
  package: current-time
  module: getCurrentTime
  requestSource: # RPC
    pulsar:
      topic: request_current_time
